# Generated by Django 5.2 on 2025-06-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_created_at_payment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
