# Generated by Django 5.2 on 2025-05-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('courses', '0003_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='certificate',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.theme'),
        ),
    ]
