# Generated by Django 5.2 on 2025-05-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_certificate_curriculum_certificate_theme'),
        ('courses', '0003_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.theme'),
        ),
    ]
